Extend `LoggingApi` with `per(...)` method
SpineEventEngine/logging pull request #10
Opened 2023-07-03 08:51 UTC by yevhenii-nadtochii

2023-07-03 11:15 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov Please take a look.

2023-07-03 13:48 UTC, armiol approved these changes
@yevhenii-nadtochii LGTM from my POV.

2023-07-03 17:00 UTC, alexander-yevsyukov requested changes
Please see my questions.

2023-07-04 08:38 UTC, yevhenii-nadtochii commented
@alexander-yevsyukov PTAL

2023-07-04 13:47 UTC, alexander-yevsyukov approved these changes
LGTM

2023-07-04 13:48 UTC, merged