Migrate `Parameter` tests to Kotlin
SpineEventEngine/logging pull request #16
Opened 2023-07-17 14:56 UTC by yevhenii-nadtochii

This PR initiates migration of original Flogger tests to Kotlin. It migrates `com.google.common.flogger.parameter` package.

I've created `:api-tests` module which is going to contain tests from `:api` translated in Kotlin. The old Java tests use JUnit 4 runner along with Truth. In Kotlin, we are going to use JUnit 5 runner and Kotest assertions. So, I've moved tests to a temporal module in order not to mix several JUnits per a single module. When all tests are migrated, `:api-tests` will be removed, and its tests will go back to `:api`.

All translated files have a link to the original source file.

The library version is bumped to `2.0.0-SNAPSHOT.195`.

2023-07-17 15:31 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov Please take a look.

2023-07-17 15:49 UTC, alexander-yevsyukov requested changes
Please see my comments and questions.

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/build.gradle.kts
> +    testImplementation("com.google.truth:truth:1.1.3") // Should be killed at the end.
> Should be killed at the end.

Instead of "kill", it is generally better to use softer terms like "removed" or "deleted".

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/build.gradle.kts
> +    testImplementation("com.google.truth:truth:1.1.3") // Should be killed at the end.
Also, "the end" is not clear. The end of what?

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/src/test/kotlin/com/google/common/flogger/parameter/ParameterSpec.kt
> + * Original Java code copied and translated from [google/flogger](https://github.com/google/flogger).
Please change this to be according to the following template:

```
${SHORT_TEST_SUITE_DESCRIPTION}

@see <a href="${ORIGINAL_JAVA_CODE_URL_AT_GITHUB}">Original Java code of Google Flogger</a>
```

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/src/test/kotlin/com/google/common/flogger/parameter/ParameterSpec.kt
> + * Original Java code copied and translated from [google/flogger](https://github.com/google/flogger).
This way we:
 * Help the reader to get the original Java code without searching for it at GitHub.
 * Save on repeating the license terms all over again. The (c) statement of the original code would be immediately accessible via following the link.

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/src/test/kotlin/com/google/common/flogger/parameter/ParameterSpec.kt
> +        assertThrows(IllegalArgumentException::class.java) {
This could be `assertThrows<IllegalArgumentException> {...}`. There was an extension function for this.

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/src/test/kotlin/com/google/common/flogger/parameter/ParameterSpec.kt
> +        assertThrows(IllegalArgumentException::class.java) {
And it could be a block function instead of full body. It's too much of a ceremony for one-liner job.

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/build.gradle.kts
> +        fun TestResult.summary(): String =
Why cannot we use our Kotlin code from `buildSrc` for this? I don't insist, just curious.

2023-07-17 15:49 UTC, alexander-yevsyukov commented on flogger/api-tests/src/test/kotlin/com/google/common/flogger/parameter/ParameterSpec.kt
> +package com.google.common.flogger.parameter
Can we move tests to our packages already?

Even if there are some which are tied to internals (package-private guts of Java code, for example), perhaps, we can repackage some of the tests?

2023-07-18 12:41 UTC, alexander-yevsyukov approved these changes
LGTM

2023-07-18 12:43 UTC, merged