Merge `:flogger-system-backend` into `:logging-backend`
SpineEventEngine/logging pull request #50
Opened 2023-09-20 16:03 UTC by yevhenii-nadtochii

2023-09-21 14:04 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL

2023-09-21 15:10 UTC, armiol requested changes
@yevhenii-nadtochii please see my comments.

And yes, I would create issues on top of your "summary" findings.

2023-09-21 15:10 UTC, armiol commented on flogger/flogger-log4j2-backend/src/main/java/com/google/common/flogger/backend/log4j2/Log4j2BackendFactory.java
> + * <p>When using Flogger's {@link io.spine.logging.backend.system.DefaultPlatform}, this
Is it still "Flogger's"?

2023-09-21 15:10 UTC, armiol commented on logging-backend/src/main/java/io/spine/logging/backend/system/AbstractLogRecord.java
> + * Copyright 2023, TeamDev. All rights reserved.
It's important.

```
Copyright 2015, The Flogger Authors; 2023, TeamDev. All rights reserved.
```

Let's apply to all similar cases.

2023-09-21 15:10 UTC, armiol commented on logging-backend/src/main/java/io/spine/logging/backend/system/package-info.java
> + * `java.util.logging` (JUL) to output log statements.
I would use `{@code ...}` in Javadoc.

2023-09-21 15:10 UTC, armiol commented on logging-backend/src/main/kotlin/io/spine/logging/backend/system/StdLoggerBackend.kt
> +     * If [wasForced] is set, forces the publishing by increasing the level
```
... is `true`...
```

2023-09-21 15:10 UTC, armiol commented on logging/build.gradle.kts
> +                // `FluentLogger2` is exposed by the deprecated `Logging` interface.
Please add more context details here. It's difficult to comprehend without being deep into the problem.

2023-09-21 15:10 UTC, armiol commented on tests/jvm-log4j-backend-our-context/build.gradle.kts
> +     * But tests make sure that the platform indeed picked up the expected
Again, to my understanding, a few steps are skipped in this explanation. Please expand.

2023-09-21 15:10 UTC, armiol commented on tests/jvm-our-backend-our-context/build.gradle.kts
> +     * Backend and context should have been added to [runtimeOnly].
Same as above.

2023-09-22 10:40 UTC, alexander-yevsyukov approved these changes
LGTM

2023-09-22 10:40 UTC, alexander-yevsyukov commented on logging-backend/src/main/java/io/spine/logging/backend/system/AbstractBackend.java
> + * @see <a href="https://github.com/google/flogger/blob/cb9e836a897d36a78309ee8badf5cad4e6a2d3d8/api/src/main/java/com/google/common/flogger/backend/system/AbstractBackend.java">
Just a thought. We probably need to consider using some URL shortener some day. There was free one from Google, but it's no longer available. I couldn't find a good alternative.

2023-09-22 13:04 UTC, alexander-yevsyukov commented on logging-backend/src/main/java/io/spine/logging/backend/system/AbstractBackend.java
> + * @see <a href="https://github.com/google/flogger/blob/cb9e836a897d36a78309ee8badf5cad4e6a2d3d8/api/src/main/java/com/google/common/flogger/backend/system/AbstractBackend.java">
@armiol, here's one option, which is free and looks as usable. Please have a look.

2023-09-22 13:05 UTC, alexander-yevsyukov commented on logging-backend/src/main/java/io/spine/logging/backend/system/AbstractBackend.java
> + * @see <a href="https://github.com/google/flogger/blob/cb9e836a897d36a78309ee8badf5cad4e6a2d3d8/api/src/main/java/com/google/common/flogger/backend/system/AbstractBackend.java">
https://free-url-shortener.rb.gy/

2023-09-22 13:49 UTC, yevhenii-nadtochii commented
@armiol PTAL

2023-09-22 15:17 UTC, armiol approved these changes

2023-09-22 15:19 UTC, merged