Implement `kmp-module` script plugin
SpineEventEngine/logging pull request #81
Opened 2023-10-13 17:13 UTC by yevhenii-nadtochii

2023-10-16 13:56 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL

2023-10-16 16:07 UTC, armiol requested changes
@yevhenii-nadtochii please see my comments. LGTM otherwise.

2023-10-16 16:07 UTC, armiol commented on buildSrc/src/main/kotlin/kmp-module.gradle.kts
> +plugins {
Let's document this file, starting with its purpose (e.g. file-level comment), and down below.

As its our first experience with extracting common parts for KMP, I would invest into documenting.

2023-10-16 16:07 UTC, armiol commented on buildSrc/src/main/kotlin/kmp-publish.gradle.kts
> +plugins {
Same as above.

The important thing to know in both files is what differs them from "pure Java" or "Kotlin JVM" modules.

2023-10-16 16:07 UTC, armiol commented on platforms/jvm-default-platform/build.gradle.kts
> +// `kaptKotlin` task is created after the configuration phase.
Please expand on the purpose.

2023-10-17 11:42 UTC, yevhenii-nadtochii commented
@armiol PTAL

2023-10-17 13:53 UTC, armiol approved these changes
@yevhenii-nadtochii thank you! LGTM.

2023-10-17 13:57 UTC, merged